const mobiles = [
  {
    name: "iPhone XR",
    price: 49000,
    brand: "Apple",
    RAM: "4GB",
    ROM: "128GB",
    OS: "iOS",
  },
  {
    name: "iPhone 7",
    price: 28500,
    brand: "Apple",
    RAM: "3GB",
    ROM: "32GB",
    OS: "iOS",
  },
  {
    name: "iPhone 8",
    price: 33000,
    brand: "Apple",
    RAM: "3GB",
    ROM: "64GB",
    OS: "iOS",
  },
  {
    name: "iPhone 11",
    price: 52000,
    brand: "Apple",
    RAM: "6GB",
    ROM: "128GB",
    OS: "iOS",
  },
  {
    name: "iPhone 12",
    price: 71000,
    brand: "Apple",
    RAM: "8GB",
    ROM: "128GB",
    OS: "iOS",
  },
  {
    name: "J1",
    price: 7500,
    brand: "Samsung",
    RAM: "3GB",
    ROM: "32GB",
    OS: "Android",
  },
  {
    name: "J2",
    price: 9500,
    brand: "Samsung",
    RAM: "4GB",
    ROM: "32GB",
    OS: "Android",
  },
  {
    name: "J5",
    price: 12700,
    brand: "Samsung",
    RAM: "6GB",
    ROM: "64GB",
    OS: "Android",
  },
  {
    name: "M32",
    price: 18300,
    brand: "Samsung",
    RAM: "6GB",
    ROM: "64GB",
    OS: "Android",
  },
  {
    name: "A25",
    price: 24600,
    brand: "Samsung",
    RAM: "8GB",
    ROM: "128GB",
    OS: "Android",
  },
  {
    name: "Note 6",
    price: 9999,
    brand: "Xiaomi",
    RAM: "3GB",
    ROM: "32GB",
    OS: "Android",
  },
  {
    name: "Note 7",
    price: 12000,
    brand: "Xiaomi",
    RAM: "6GB",
    ROM: "64GB",
    OS: "Android",
  },
  {
    name: "Note 8",
    price: 14100,
    brand: "Xiaomi",
    RAM: "8GB",
    ROM: "128GB",
    OS: "Android",
  },
  {
    name: "Note 9",
    price: 17900,
    brand: "Xiaomi",
    RAM: "8GB",
    ROM: "128GB",
    OS: "Android",
  },
  {
    name: "X4",
    price: 11300,
    brand: "Realme",
    RAM: "3GB",
    ROM: "32GB",
    OS: "Android",
  },
  {
    name: "X5",
    price: 12900,
    brand: "Realme",
    RAM: "4GB",
    ROM: "64GB",
    OS: "Android",
  },
  {
    name: "X6",
    price: 15800,
    brand: "Realme",
    RAM: "6GB",
    ROM: "128GB",
    OS: "Android",
  },
  {
    name: "X7",
    price: 19300,
    brand: "Realme",
    RAM: "8GB",
    ROM: "128GB",
    OS: "Android",
  },
];

module.exports.mobiles = mobiles;
